version: "3"
  
services: 
  app: 
    build: 
      context: .
    # command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma.rb -e production
    volumes: 
      - ".:/spring_web"
      - "public-data:/spring_web/public"
      - "tmp-data:/spring_web/tmp"
      - "log-data:/spring_web/log"
    ports: 
      - "3000:3000"
    environment: 
      - "DATABASE_PASSWORD=friendship3312T"
    tty: true
    stdin_open: true
    depends_on: 
      - db
    networks:
      - spring_web_network
  
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes: 
      - "db-data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=friendship3312T"
    networks:
      - spring_web_network
    
  # web:
  #   build: 
  #     context: ./nginx_docker
  #   volumes: 
  #     - "public-data:/spring_web/public"
  #     - "tmp-data:/spring_web/tmp"
  #   ports: 
  #     - "80:80"
  #   depends_on: 
  #     - app
  #   networks:
  #     - spring_web_network
     
  # webpacker:
  #   build: .
  #   volumes:
  #     - .:/spring_web
  #   command: ./bin/webpack-dev-server
  #   environment:
  #     WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  #   ports:
  #     - "3035:3035"

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:

networks: 
  spring_web_network:
    external: true
      
     
